name: Build Docker

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t myuser/sample-app:${{ github.sha }} .

      - name: Push Image
        run: |
           docker push myuser/sample-app:${{ github.sha }}  
